export enum ExpressionAtom {
    // Math
    add = 'add',
    mul_overloaded = 'mul_overloaded',
    sub = 'sub',
    truediv = 'truediv',
    ediv = 'ediv',
    mod = 'mod',
    lsl = 'lsl',
    lsr = 'lsr',
    // Comparison
    eq = 'eq',
    neq = 'neq',
    lt = 'lt',
    gt = 'gt',
    le = 'le',
    ge = 'ge',
    // Logic
    and = 'and',
    or = 'or',
    xor = 'xor',
    // Unary
    not = 'not',
    neg = 'neg',
    // Blockchain property
    amount = 'amount',
    balance = 'balance',
    chain_id = 'chain_id',
    level = 'level',
    now = 'now',
    self = 'self',
    self_address = 'self_address',
    sender = 'sender',
    source = 'source',
    total_voting_power = 'total_voting_power',
    voting_power = 'voting_power',
    // Operation
    operations = 'operations',
    transfer = 'transfer',
    set_delegate = 'set_delegate',
    create_contract = 'create_contract',
    // List instructions
    cons = 'cons',
    // Variant
    openVariant = 'openVariant',
    isVariant = 'isVariant',
    cases_arg = 'cases_arg',
    variant_arg = 'variant_arg',
    // Crypto
    blake2b = 'blake2b',
    sha256 = 'sha256',
    sha512 = 'sha512',
    sha3 = 'sha3',
    keccak = 'keccak',
    check_signature = 'check_signature',
    // Integer
    toInt = 'toInt',
    isNat = 'isNat',
    abs = 'abs',
    // Generic
    size = 'size',
    concat = 'concat',
    contains = 'contains',
    items = 'items',
    update_map = 'update_map',
    getItem = 'getItem',
    getItemDefault = 'getItemDefault',
    getItemMessage = 'getItemMessage',
    attr = 'attr',
    params = 'params',
    lambdaParams = 'lambdaParams',
    getLocal = 'getLocal',
    iter = 'iter',
    contract = 'contract',
    call_lambda = 'call_lambda',
    view = 'view',
    first = 'first',
    second = 'second',
    pack = 'pack',
    unpack = 'unpack',
    type_annotation = 'type_annotation',
    to_address = 'to_address',
    implicit_account = 'implicit_account',
    sapling_empty_state = 'sapling_empty_state',
    sapling_verify_update = 'sapling_verify_update',
    pairing_check = 'pairing_check',
}

export default ExpressionAtom;
