/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    sidebar: [
        {
            type: 'doc',
            label: 'Overview',
            id: 'overview',
        },
        {
            type: 'category',
            collapsed: false,
            collapsible: false,
            label: 'Contract Structure',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'contract_api',
                },
            ],
        },
        {
            type: 'doc',
            label: 'Values',
            id: 'literals',
        },
        {
            type: 'doc',
            label: 'Types',
            id: 'types',
        },
        {
            type: 'category',
            collapsed: false,
            collapsible: false,
            label: 'Expressions',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'expressions',
                },
            ],
        },
        {
            type: 'category',
            collapsed: false,
            collapsible: false,
            label: 'Statements',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'statements',
                },
            ],
        },
        {
            type: 'category',
            collapsed: false,
            collapsible: false,
            label: 'Contracts',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'contracts',
                },
            ],
        },
    ],
};

module.exports = sidebars;
